{
 "title": "Alloy / OpenTelemetry",
 "tags": [ "alloy-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(alloy_component_controller_running_components, cluster)\n"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=\"$cluster\"}, namespace)\n"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=\"$cluster\", namespace=\"$namespace\"}, instance)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Receivers for traces [otelcol.receiver]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Accepted spans",
   "type": "timeseries",
   "description": "Number of spans successfully pushed into the pipeline.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(receiver_accepted_spans_ratio_total{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "{{ pod }} / {{ transport }}"
    }
   ]
  },
  {
   "title": "Refused spans",
   "type": "timeseries",
   "description": "Number of spans that could not be pushed into the pipeline.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(receiver_refused_spans_ratio_total{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "{{ pod }} / {{ transport }}"
    }
   ]
  },
  {
   "title": "RPC server duration",
   "type": "heatmap",
   "description": "The duration of inbound RPCs.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (increase(rpc_server_duration_milliseconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\", rpc_service=\"opentelemetry.proto.collector.trace.v1.TraceService\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Batching of logs, metrics, and traces [otelcol.processor.batch]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Number of units in the batch",
   "type": "heatmap",
   "description": "Number of spans, metric datapoints, or log lines in a batch\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (le) (increase(processor_batch_batch_send_size_ratio_bucket{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Distinct metadata values",
   "type": "timeseries",
   "description": "Number of distinct metadata value combinations being processed\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "processor_batch_metadata_cardinality_ratio{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Timeout trigger",
   "type": "timeseries",
   "description": "Number of times the batch was sent due to a timeout trigger\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "rate(processor_batch_timeout_trigger_send_ratio_total{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Exporters for traces [otelcol.exporter]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Exported sent spans",
   "type": "timeseries",
   "description": "Number of spans successfully sent to destination.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(exporter_sent_spans_ratio_total{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Exported failed spans",
   "type": "timeseries",
   "description": "Number of spans in failed attempts to send to destination.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "rate(exporter_send_failed_spans_ratio_total{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}